### ISSUE TITLE
TypeScript Definitions

### ISSUE THREAD

**Issue by vivekweb2013** [lukeed/tinydate#10]
With the import statement I get a warning in vscode saying

`import tinydate from 'tinydate';`

> module "/Users/###/###/node_modules/tinydate/dist/tinydate"
> Could not find a declaration file for module 'tinydate'. '/Users/###/###/node_modules/tinydate/dist/tinydate.js' implicitly has an 'any' type.
>   Try `npm install @types/tinydate` if it exists or add a new declaration (.d.ts) file containing `declare module 'tinydate';`ts(7016)

![image](https://user-images.githubusercontent.com/7036736/85978516-83a8db00-b9fc-11ea-8946-216f520c04c0.png)

**Comment by lukeed** [comment]
It's because you're either using typescript or an editor with intellisense for typescript (eg, vscode). I can add type definitions

**Comment by vivekweb2013** [comment]
Yes please add the type definition as this is the only warning shown in my well written project 😜

**Comment by lukeed** [comment]
Available in `1.3.0` :)
