### ISSUE TITLE
Timezone Change

### ISSUE THREAD

**Issue by ghost** [lukeed/tinydate#3]
Please add that you can change the Timezone

**Comment by lukeed** [comment]
I'm sorry, what do you mean? 

You provide `tinydate` with a `Date` &mdash; or else it creates a `new Date` w/ current (or default) timezone settings. It doesn't _change_ anything.

**Comment by ghost** [comment]
Oh sorry i used heroku and i didnt know how to change timezones and i was confused because it has the right time on runkit

**Comment by lukeed** [comment]
No worries 👍 Thanks!
