### ISSUE TITLE
another small date format lib

### ISSUE THREAD

**Issue by leeoniya** [lukeed/tinydate#4]
hey @lukeed 

here's an oldie but goodie. this has been my goto for a long time. might be worth adding as alternative & benching :)

http://blog.stevenlevithan.com/archives/date-time-format

**Comment by lukeed** [comment]
Hey @leeoniya, thanks! 

I think this is the first JS lib in article-format I've seen in yearrrrrs 😆 

Here are the results – I don't really think I should be committing the code since it's not mine (or easily accessible on npm), but I can if you think it's important

```
tinydate           x  162,809,047 ops/sec ±0.24% (95 runs sampled)
tinytime           x   44,159,145 ops/sec ±0.26% (95 runs sampled)
time-stamp         x      860,051 ops/sec ±1.24% (89 runs sampled)
date-time-format   x      197,892 ops/sec ±0.74% (92 runs sampled)
```
