### ISSUE TITLE
Milliseconds support

### ISSUE THREAD

**Issue by fabiospampinato** [lukeed/tinydate#5]
An `{ms}` token for milliseconds would be great to have.

**Comment by lukeed** [comment]
Nice, yeah I think so. But it looks like `fff` is a much more common format (C#, .NET, java, matlab, etc). That also plays nicer with the existing code.

Sound reasonable?

**Comment by fabiospampinato** [comment]
I've probably never met the "fff" token before, but I guess it would work. The nice thing about it is that it better represents how many numbers are going to get printed.

**Comment by lukeed** [comment]
Aye, that's exactly how every other lang treats it & how the current code determines the number of digits to slice :)

Will do this now

**Comment by fabiospampinato** [comment]
Super quick, thanks!

**Comment by lukeed** [comment]
No problem! Thanks for the idea 👍 Now released as `1.1.0`~!
