### ISSUE TITLE
i18n support using Intl.DateTimeFormat

### ISSUE THREAD

**Issue by mhf-ir** [lukeed/tinydate#6]
How about i18n support?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat

https://caniuse.com/#feat=internationalization

**Comment by lukeed** [comment]
Hey, `tinydate` is actually feature complete. It works with the template that you provide it. All it's meant to do is render into that template as fast as possible.

Plus, using `Intl` is very simple as is (and significantly slower) so don't think there's much need or benefit in wrapping it.

Tinydate is basically meant for high throughput scenarios, like logging with timestamps.

Thanks for the suggestion though 😊
